default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWSQL_ACCOUNT') }}"
      user: "{{ env_var('SNOWSQL_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: "{{ env_var('SNOWSQL_ROLE') }}"
      database: "{{ env_var('SNOWSQL_DATABASE') }}"
      warehouse: "{{ env_var('SNOWSQL_WAREHOUSE') }}"
      schema: PUBLIC
      threads: 1
      client_session_keep_alive: False